const images = {
    logo: require('./logo/logo.png'),
    front_bot_logo: require('./bots/FrontBotLogo.png'),
    icn_channel: { uri: 'icn_channel' },
    icn_chatbot: { uri: 'icn_chatbot' },
    icn_configure: { uri: 'icn_configure' },
    icn_contact: { uri: 'icn_contact' },
    icn_fav: { uri: 'icn_fav' },
    icn_alerts: { uri: 'icn_alerts' },
    icn_hospitaity: { uri: 'icn_hospitaity' },
    icn_news: { uri: 'icn_news' },
    icn_retail: { uri: 'icn_retail' },
    icn_shopping: { uri: 'icn_shopping' },
    icn_travel: { uri: 'icn_travel' },
    btn_add: { uri: 'btn_add' },
    icn_delete: { uri: 'icn_delete' },
    btn_add_list: { uri: 'botlist_btn_add' },
    btn_close: { uri: 'btn_close' },
    icn_filter: { uri: 'icn_filter' },
    icn_search: { uri: 'icn_search' },
    authentication_logo: { uri: 'AuthenticationLogo' },
    bots: { uri: 'bots' },
    botsbg: { uri: 'botsbg' },
    channels_bot_logo: { uri: 'ChannelsBotLogo' },
    emojis: { uri: 'emojis' },
    location_services: { uri: 'LocationServices' },
    push_notifications: { uri: 'PushNotifications' },
    btn_back: { uri: 'btn_back' },
    btn_download: { uri: 'btn_download' },
    btn_more: { uri: 'btn_more' },
    btn_record: { uri: 'btn_record' },
    btn_send: { uri: 'btn_send' },
    checkmark_normal: { uri: 'checkmark_normal' },
    checkmark_selected: { uri: 'checkmark_selected' },
    btn_close_slider: { uri: 'purple_btn_close' },
    btn_info: { uri: 'btn_info' },
    icn_slider: { uri: 'icn_slider' },
    walkthrough_image: require('./walkthrough/image.png'),
    splash_page_logo: { uri: 'FM-logo-landing page' },
    user_image: { uri: 'user_image' }
};

export default images;

