const colors = {
    PRIMARY_COLOR: '#638dff', //
    PRIMARY_TRANSPERENT_COLOR: '#638dff33',
    DARK: '#2a2d3c',
    PALE_GREY: '#f6f8fc',
    COOL_GREY: '#9c9ea7',
    GUNMETAL: '#44485a',
    CTA: '#638dff',
    RED: '#e5453b'
};

const AppColors = {
    //main colors for app
    appBackground: '#fff',
    toolbarBackground: colors.PRIMARY_COLOR,
    bottomTabBarBackground: '#fff',
    chatBackground: '#f6f8fc',
    chatTextColor: colors.GUNMETAL,
    primaryButtonColor: colors.CTA,
    primaryButtonText: '#fff',
    primaryButtonColorDisabled: '#aeb8d6',
    primaryButtonTextDisabled: '#e8ecf8',
    secondaryButtonColor: '#e0e8ff',
    secondaryButtonColorDisabled: '#e8ecf8',
    secondaryButtonText: '#638dff',
    secondaryButtonTextDisabled: '#aeb8d6',
    actionButtons: '#9c9ea7',
    primaryTextColor: colors.GUNMETAL,
    chatTitle: colors.DARK,
    chatSubTitle: colors.DARK,
    descriptionText: '#9c9ea7',
    itemDevider: '#f1f1f1',
    itemDevider2: colors.PALE_GREY,
    formLable: '#9c9ea7',
    cursorColor: '#9c9ea7',
    formText: '#2a2d3c',
    formPlaceholderText: colors.COOL_GREY,
    formTextDisabled: '#666666',
    formBorderColor: '#C4D8FF',
    formItemBackgroundColor: '#F4F4F4',
    formItemBackgroundColorDisabled: colors.PALE_GREY,
    switchTrackTrue: '#ACE9C5',
    switchTrackFalse: '#EBEBEB',
    switchThumbTrue: '#2FC76F',
    switchThumbFalse: '#CCCCCC',
    tableItemBackground: '#fff',
    tableDeatilKey: '#9c9ea7',
    tableDeatilValue: '#2a2d3c',
    timelineMessageBackground: '#f6f8fc',
    timelineMessageItem: '#fff',
    innerTabBackground: colors.PALE_GREY,
    innerTabActiveTint: colors.PRIMARY_COLOR,
    frontmLightBlue: colors.PRIMARY_COLOR, // primary app color
    primaryColor: colors.PRIMARY_COLOR,
    fullScreenMessageBackgroundV2: '#f4f4f4',
    contentBackgroundColor: '#fff',
    contentBackgroundColorSecondary: colors.PALE_GREY,
    chatUser: 'rgb(42,45,60)',
    red: colors.RED,
    dialerTextAreaBackground: 'rgba(47,199,111,1)',
    toastText: '#fff',
    toastBackground: '#2a2d3c',
    toastTextAlternate: '#2a2d3c',
    toastBacgroundAlternate: '#fffae6',
    // end of main colors

    frontmLightBlueTransparent: colors.PRIMARY_TRANSPERENT_COLOR,
    activeTabColor: colors.PRIMARY_COLOR,
    accent: colors.PRIMARY_COLOR,
    frontmIncativeTab: '#cdcfd3',
    titleText: '#171313',

    tabBackground: colors.PRIMARY_COLOR,
    secondaryBackground: '#e5f6fa',
    formDevider: '#e8e8e8',
    background: 'rgb(219,225,229)',
    black: colors.DARK,
    borderBottom: 'rgba(91,91,91,0.2)',
    botChatBubbleColor: colors.PRIMARY_COLOR,
    chatLeftTextColor: 'rgba(74,74,74,1)',
    chatRightTextColor: 'rgba(245,255,255,1)',
    criticalYellow: 'rgba(255,246,205,1)',
    darkGray: 'rgb(169,169,169)',
    disabledButton: 'rgba(255,255,255,0.2)',
    disabledGray: 'rgb(228,228,228)',
    green: 'rgba(47,199,111,1)',
    // header: 'rgb(79,41,191)',
    grey: 'rgba(102,102,102,1)',
    headerBlack: 'rgba(3,3,3,1)',
    headerTextInputPlaceholder: 'rgb(210,210,210)',
    modalBackground: 'rgba(24,24,24,0.8)',
    orangeYellow: 'rgb(231,97,33)',

    rightArrow: 'rgb(192,192,192)',
    satelliteMode: 'rgba(255,238,237,1)',
    statusBarBackgroundColor: 'rgb(255,192,203)',
    stdNotifBlue: 'rgba(205,244,255,1)',
    tabText: 'rgba(255,255,255,0.6)',
    textBlack: '#4A4A4A',
    textDarkGrey: '#666666',
    textField: 'rgba(100,100,100,0.1)',
    translucentDark: 'rgba(24,24,24,0.3)',
    transparent: 'rgba(0,0,0,0)',
    white: 'rgb(255,255,255)',
    fullScreenMessageBackground: 'rgb(248,248,248)',

    deviderGrey: '#f4f4f4',
    formTextInput: '#2a2d3c',
    formTextInputDisabledBG: '#f4f4f4',

    formTextInputLable: 'rgb(42,45,60)',
    formDelete: colors.RED,
    formSelectedItem: '#e5f6fa',
    formNonSelectedItem: '#dedede',

    menuSubLable: '#44485a',
    menuSubLableDescription: '#44485a80',
    menuDefaultColor: colors.PRIMARY_COLOR,
    videoControlBackground: '#2a2d3c',
    videoCallIcons: '#9C9EA6',
    videoCallIconBackground: '#454859',
    videoCallIconSelected: '#63C378',
    headerGreyBtn: '#9c9ea7',
    searchBorder: '#e8e8e8',
    inactiveTabColor: '#94969d',
    toggleOnColor: '#2fc76f', // green teal new ui
    toggleOffColor: '#e9e9ea',

    textInputDefault: 'rgba(0,0,0,0.8)',
    tableChekBox: '#c4d8ff',
    tableCheckboxSelected: colors.PRIMARY_COLOR,
    bgRippleColor: '#e0f0fc', // new UI chat
    textRippleColor: '#0096fb', // new UI chat
    iconColorNew: '#dedede',
    gunmetal: '#44485a',
    checkMark: '#00a7d6',
    errorRed: colors.RED,
    paleGrey: '#f6f8fc',
    socialFilterItemBorder: `rgba(79,91,125,0.2)`,
    socialAuther: '#4f5b7d',
    socialPostTime: '#959caa',
    titleChat: 'rgb(42,45,60)',
    textLable1: '#4f5b7d',
    textLableCool: 'rgb(156,158,167)',
    deviderLargeBg: 'rgb(246,248,252)',

    // for different button on both ocs and onship
    rejectButtonBgColor: '#fceceb',
    rejectButtonTxtColor: 'rgb(229,69,59)'
};
export default AppColors;
