
export default {
    GOOGLE_ANALYTICS_TRACKINGID: 'UA-37782731-2',
    GA_EVENT_CATEGORY_APP_LAUNCHED: 'App Launched',
    GA_EVENT_CATEGORY_BOT_OPENED: 'Bot Opened',
    GA_EVENT_ACTION_APP_LAUNCHED:'App Opened'
}