// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contactsservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MatchedUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ContactsserviceRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ContactsserviceRoot : GPBRootObject
@end

#pragma mark - SearchQuery

typedef GPB_ENUM(SearchQuery_FieldNumber) {
  SearchQuery_FieldNumber_QueryString = 1,
};

@interface SearchQuery : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *queryString;

@end

#pragma mark - UserIdList

typedef GPB_ENUM(UserIdList_FieldNumber) {
  UserIdList_FieldNumber_UserIdsArray = 1,
};

@interface UserIdList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *userIdsArray;
/** The number of items in @c userIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userIdsArray_Count;

@end

#pragma mark - EmailIdList

typedef GPB_ENUM(EmailIdList_FieldNumber) {
  EmailIdList_FieldNumber_EmailIdsArray = 1,
};

@interface EmailIdList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *emailIdsArray;
/** The number of items in @c emailIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger emailIdsArray_Count;

@end

#pragma mark - AgentGuardBoolResponse

typedef GPB_ENUM(AgentGuardBoolResponse_FieldNumber) {
  AgentGuardBoolResponse_FieldNumber_Error = 1,
  AgentGuardBoolResponse_FieldNumber_ContentArray = 2,
};

@interface AgentGuardBoolResponse : GPBMessage

@property(nonatomic, readwrite) int32_t error;

@property(nonatomic, readwrite, strong, null_resettable) GPBBoolArray *contentArray;
/** The number of items in @c contentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentArray_Count;

@end

#pragma mark - FindResponse

typedef GPB_ENUM(FindResponse_FieldNumber) {
  FindResponse_FieldNumber_Error = 1,
  FindResponse_FieldNumber_ContentArray = 2,
  FindResponse_FieldNumber_ErrorMessage = 3,
};

@interface FindResponse : GPBMessage

@property(nonatomic, readwrite) int32_t error;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MatchedUser*> *contentArray;
/** The number of items in @c contentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - MatchedUser

typedef GPB_ENUM(MatchedUser_FieldNumber) {
  MatchedUser_FieldNumber_UserName = 1,
  MatchedUser_FieldNumber_UserId = 2,
};

@interface MatchedUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
