# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'frontm_mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for frontm_mobile
  # pod 'FBSDKCoreKit', :inhibit_warnings => true
  # pod 'FBSDKLoginKit', :inhibit_warnings => true
  # pod 'FBSDKShareKit', :inhibit_warnings => true
  pod 'TwilioVoice', '~> 2.0.0', :inhibit_warnings => true
  #pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'
  #pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  pod 'gRPC-ProtoRPC', :inhibit_warnings => true
  pod 'Frontm', :path => '.', :inhibit_warnings => true

  #pod 'react-native-blur', :path => '../node_modules/react-native-blur'

end
