// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queue.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MapFieldEntry;
@class Message;
@class MessageDetails;
@class PreviousMessage;
@class QueueMessage;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - QueueRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface QueueRoot : GPBRootObject
@end

#pragma mark - Empty

@interface Empty : GPBMessage

@end

#pragma mark - QueueParams

typedef GPB_ENUM(QueueParams_FieldNumber) {
  QueueParams_FieldNumber_Conversation = 1,
  QueueParams_FieldNumber_BotId = 2,
  QueueParams_FieldNumber_Timestamp = 3,
};

typedef GPB_ENUM(QueueParams_PreviousMessages_OneOfCase) {
  QueueParams_PreviousMessages_OneOfCase_GPBUnsetOneOfCase = 0,
  QueueParams_PreviousMessages_OneOfCase_Conversation = 1,
  QueueParams_PreviousMessages_OneOfCase_BotId = 2,
  QueueParams_PreviousMessages_OneOfCase_Timestamp = 3,
};

@interface QueueParams : GPBMessage

@property(nonatomic, readonly) QueueParams_PreviousMessages_OneOfCase previousMessagesOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *conversation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *botId;

@property(nonatomic, readwrite) int64_t timestamp;

@end

/**
 * Clears whatever value was set for the oneof 'previousMessages'.
 **/
void QueueParams_ClearPreviousMessagesOneOfCase(QueueParams *message);

#pragma mark - QueueInput

typedef GPB_ENUM(QueueInput_FieldNumber) {
  QueueInput_FieldNumber_SessionId = 1,
};

@interface QueueInput : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@end

#pragma mark - Message

typedef GPB_ENUM(Message_FieldNumber) {
  Message_FieldNumber_Id_p = 1,
  Message_FieldNumber_Content = 2,
};

@interface Message : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - MessageList

typedef GPB_ENUM(MessageList_FieldNumber) {
  MessageList_FieldNumber_MessagesArray = 1,
};

@interface MessageList : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Message*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

#pragma mark - QueueResponse

typedef GPB_ENUM(QueueResponse_FieldNumber) {
  QueueResponse_FieldNumber_OnSatellite = 1,
  QueueResponse_FieldNumber_QueueMsgsArray = 2,
  QueueResponse_FieldNumber_PreviousMsgsArray = 3,
  QueueResponse_FieldNumber_ErrorMessage = 4,
};

@interface QueueResponse : GPBMessage

@property(nonatomic, readwrite) BOOL onSatellite;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<QueueMessage*> *queueMsgsArray;
/** The number of items in @c queueMsgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger queueMsgsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PreviousMessage*> *previousMsgsArray;
/** The number of items in @c previousMsgsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger previousMsgsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorMessage;

@end

#pragma mark - PreviousMessage

typedef GPB_ENUM(PreviousMessage_FieldNumber) {
  PreviousMessage_FieldNumber_MessageId = 1,
  PreviousMessage_FieldNumber_ContentType = 2,
  PreviousMessage_FieldNumber_CreatedOn = 3,
  PreviousMessage_FieldNumber_ContentArray = 4,
};

@interface PreviousMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contentType;

@property(nonatomic, readwrite) int32_t createdOn;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *contentArray;
/** The number of items in @c contentArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger contentArray_Count;

@end

#pragma mark - QueueMessage

typedef GPB_ENUM(QueueMessage_FieldNumber) {
  QueueMessage_FieldNumber_UserId = 1,
  QueueMessage_FieldNumber_Conversation = 2,
  QueueMessage_FieldNumber_Bot = 3,
  QueueMessage_FieldNumber_CreatedOn = 4,
  QueueMessage_FieldNumber_CreatedBy = 5,
  QueueMessage_FieldNumber_ContentType = 6,
  QueueMessage_FieldNumber_MessageId = 7,
  QueueMessage_FieldNumber_RequestUuid = 8,
  QueueMessage_FieldNumber_DetailsArray = 9,
  QueueMessage_FieldNumber_Error = 10,
};

@interface QueueMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *conversation;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bot;

@property(nonatomic, readwrite) int32_t createdOn;

@property(nonatomic, readwrite, copy, null_resettable) NSString *createdBy;

@property(nonatomic, readwrite) int32_t contentType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *messageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestUuid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageDetails*> *detailsArray;
/** The number of items in @c detailsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger detailsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

@end

#pragma mark - MapFieldEntry

typedef GPB_ENUM(MapFieldEntry_FieldNumber) {
  MapFieldEntry_FieldNumber_Key = 1,
  MapFieldEntry_FieldNumber_Value = 2,
};

@interface MapFieldEntry : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;

@end

#pragma mark - MessageDetails

typedef GPB_ENUM(MessageDetails_FieldNumber) {
  MessageDetails_FieldNumber_Message = 1,
  MessageDetails_FieldNumber_Error = 2,
  MessageDetails_FieldNumber_InfoArray = 3,
};

@interface MessageDetails : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

/**    optional google.protobuf.Any info = 3; */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MapFieldEntry*> *infoArray;
/** The number of items in @c infoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger infoArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
