// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: queueservice.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Queueservice.pbobjc.h"
 #import "Commonmessages.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - QueueserviceRoot

@implementation QueueserviceRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - QueueserviceRoot_FileDescriptor

static GPBFileDescriptor *QueueserviceRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"queue"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - Message

@implementation Message

@dynamic id_p;
@dynamic content;

typedef struct Message__storage_ {
  uint32_t _has_storage_[1];
  NSString *id_p;
  NSString *content;
} Message__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Message__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "content",
        .dataTypeSpecific.className = NULL,
        .number = Message_FieldNumber_Content,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Message__storage_, content),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Message class]
                                     rootClass:[QueueserviceRoot class]
                                          file:QueueserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Message__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MessageList

@implementation MessageList

@dynamic messagesArray, messagesArray_Count;

typedef struct MessageList__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *messagesArray;
} MessageList__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "messagesArray",
        .dataTypeSpecific.className = GPBStringifySymbol(Message),
        .number = MessageList_FieldNumber_MessagesArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MessageList__storage_, messagesArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MessageList class]
                                     rootClass:[QueueserviceRoot class]
                                          file:QueueserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MessageList__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - QueueResponse

@implementation QueueResponse

@dynamic onSatellite;
@dynamic queueMsgsArray, queueMsgsArray_Count;
@dynamic errorMessage;
@dynamic error;

typedef struct QueueResponse__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *queueMsgsArray;
  NSString *errorMessage;
  NSString *error;
} QueueResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "onSatellite",
        .dataTypeSpecific.className = NULL,
        .number = QueueResponse_FieldNumber_OnSatellite,
        .hasIndex = 0,
        .offset = 1,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "queueMsgsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(QueueMessage),
        .number = QueueResponse_FieldNumber_QueueMsgsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(QueueResponse__storage_, queueMsgsArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "errorMessage",
        .dataTypeSpecific.className = NULL,
        .number = QueueResponse_FieldNumber_ErrorMessage,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(QueueResponse__storage_, errorMessage),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "error",
        .dataTypeSpecific.className = NULL,
        .number = QueueResponse_FieldNumber_Error,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(QueueResponse__storage_, error),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[QueueResponse class]
                                     rootClass:[QueueserviceRoot class]
                                          file:QueueserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(QueueResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\001\013\000\002\000queueMsgs\000\003\014\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - QueueMessage

@implementation QueueMessage

@dynamic userId;
@dynamic conversation;
@dynamic bot;
@dynamic createdOn;
@dynamic createdBy;
@dynamic contentType;
@dynamic messageId;
@dynamic requestUuid;
@dynamic detailsArray, detailsArray_Count;
@dynamic error;

typedef struct QueueMessage__storage_ {
  uint32_t _has_storage_[1];
  int32_t createdOn;
  int32_t contentType;
  NSString *userId;
  NSString *conversation;
  NSString *bot;
  NSString *createdBy;
  NSString *messageId;
  NSString *requestUuid;
  NSMutableArray *detailsArray;
  NSString *error;
} QueueMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "userId",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_UserId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, userId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "conversation",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_Conversation,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, conversation),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "bot",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_Bot,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, bot),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "createdOn",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_CreatedOn,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, createdOn),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "createdBy",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_CreatedBy,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, createdBy),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contentType",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_ContentType,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, contentType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "messageId",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_MessageId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, messageId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "requestUuid",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_RequestUuid,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, requestUuid),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "detailsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(MessageDetails),
        .number = QueueMessage_FieldNumber_DetailsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, detailsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "error",
        .dataTypeSpecific.className = NULL,
        .number = QueueMessage_FieldNumber_Error,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(QueueMessage__storage_, error),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[QueueMessage class]
                                     rootClass:[QueueserviceRoot class]
                                          file:QueueserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(QueueMessage__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\006\001\006\000\004\t\000\005\t\000\006\013\000\007\t\000\010\013\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MessageDetails

@implementation MessageDetails

@dynamic message;
@dynamic error;
@dynamic info;
@dynamic options;

typedef struct MessageDetails__storage_ {
  uint32_t _has_storage_[1];
  NSString *message;
  NSString *error;
  NSString *info;
  NSString *options;
} MessageDetails__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "message",
        .dataTypeSpecific.className = NULL,
        .number = MessageDetails_FieldNumber_Message,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MessageDetails__storage_, message),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "error",
        .dataTypeSpecific.className = NULL,
        .number = MessageDetails_FieldNumber_Error,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MessageDetails__storage_, error),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "info",
        .dataTypeSpecific.className = NULL,
        .number = MessageDetails_FieldNumber_Info,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MessageDetails__storage_, info),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "options",
        .dataTypeSpecific.className = NULL,
        .number = MessageDetails_FieldNumber_Options,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MessageDetails__storage_, options),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MessageDetails class]
                                     rootClass:[QueueserviceRoot class]
                                          file:QueueserviceRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MessageDetails__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
