const ROUTER_SCENE_KEYS = {
    'lightbox': 'lightbox',
    'main': 'main',
    'timeline': 'timeline',
    'chatScene': 'chatScene',
    'botChat': 'botChat',
    'peopleChat': 'peopleChat',
    'slider': 'slider',
    'webview': 'webview',
    'addContacts': 'addContacts',
    'info': 'info',
    'form': 'form',
    'botStore': 'botStore',
    'botFilter': 'botFilter',
    'botList': 'botList',
    'installedBots' : 'installedBots',
    'barCodeScanner' : 'barCodeScanner',
    'launch': 'launch',
    'mapView': 'mapView',
    'imageViewer': 'imageViewer',
    'SNRChart': 'SNRChart',
    'conversations': 'conversations',
    'favoriteMessage' : 'favoriteMessage',
    'locationPicker': 'locationPicker',
    'onboarding': 'onboarding',
    'videoRecorder': 'videoRecorder',
    'channelsList': 'channelsList'
};

export default ROUTER_SCENE_KEYS;
