const ROUTER_SCENE_KEYS = {
    lightbox: 'lightbox',
    main: 'main',
    timeline: 'timeline',
    chatScene: 'chatScene',
    botChat: 'botChat',
    peopleChat: 'peopleChat',
    channelChat: 'channelChat',
    slider: 'slider',
    webview: 'webview',
    addContacts: 'addContacts',
    info: 'info',
    form: 'form',
    botStore: 'botStore',
    botFilter: 'botFilter',
    botList: 'botList',
    barCodeScanner: 'barCodeScanner',
    launch: 'launch',
    mapView: 'mapView',
    imageViewer: 'imageViewer',
    SNRChart: 'SNRChart',
    conversations: 'conversations',
    favoriteMessage: 'favoriteMessage',
    locationPicker: 'locationPicker',
    onboarding: 'onboarding',
    videoRecorder: 'videoRecorder',
    channelsList: 'channelsList',
    phone: 'phone',
    dialler: 'dialler',
    loginScreen: 'loginScreen',
    signupScreen: 'signupScreen',
    swiperScreen: 'swiperScreen',
    confirmationScreen: 'confirmationScreen',
    resendCodeScreen: 'resendCodeScreen'
};

export default ROUTER_SCENE_KEYS;
