const images = {
    logo: require('./logo/logo.png'),
    front_bot_logo: require('./bots/FrontBotLogo.png'),
    icn_channel: require('./addlist/icn_channel.png'),
    icn_chatbot: require('./addlist/icn_chatbot.png'),
    icn_configure: require('./addlist/icn_configure.png'),
    icn_contact: require('./addlist/icn_contact.png'),
    icn_fav: require('./addlist/icn_fav.png'),
    icn_alerts: require('./botcategories/icn_alerts.png'),
    icn_hospitaity: require('./botcategories/icn_hospitaity.png'),
    icn_news: require('./botcategories/icn_news.png'),
    icn_retail: require('./botcategories/icn_retail.png'),
    icn_shopping: require('./botcategories/icn_shopping.png'),
    icn_travel: require('./botcategories/icn_travel.png'),
    btn_add: require('./botinstall/btn_add.png'),
    icn_delete: require('./botinstall/icn_delete.png'),
    btn_add_list: require('./botlist/btn_add.png'),
    btn_close: require('./botlist/btn_close.png'),
    icn_filter: require('./botlist/icn_filter.png'),
    icn_search: require('./botlist/icn_search.png'),
    authentication_logo: require('./bots/AuthenticationLogo.png'),
    bots: require('./bots/bots.png'),
    botsbg: require('./bots/botsbg.png'),
    channels_bot_logo: require('./bots/ChannelsBotLogo.png'),
    emojis: require('./bots/emojis.png'),
    location_services: require('./bots/LocationServices.png'),
    push_notifications: require('./bots/PushNotifications.png'),
    btn_back: require('./chat/btn_back.png'),
    btn_download: require('./chat/btn_download.png'),
    btn_more: require('./chat/btn_more.png'),
    btn_record: require('./chat/btn_record.png'),
    btn_send: require('./chat/btn_send.png'),
    checkmark_normal: require('./contact/checkmark_normal.png'),
    checkmark_selected: require('./contact/checkmark_selected.png'),
    btn_close_slider: { uri: 'purple_btn_close' },
    btn_info: require('./slider/btn_info.png'),
    icn_slider: require('./slider/icn_slider.png'),
    walkthrough_image: require('./walkthrough/image.png'),
    gsm: require('./icons/gsm.png'),
    satellite: require('./icons/satellite.png'),
    user_image: require('./chat/user_image.png'),
    splash_page_logo: { uri: 'FM-logo-landing page' },
    trail_arrow: require('./map/trail_arrow.png'),
    btn_pressed_facebook: require('./facebook/btn-facebook-pressed.png'),
    btn_pressed_google: require('./google/btn-google-pressed.png'),
    btn_facebook: require('./btn-facebook/btn-facebook.png'),
    btn_google: require('./btn-google/btn-google.png'),
    preview_slider_1: require('./preview-slide-1/preview-slide-1.png'),
    preview_slider_2: require('./preview-slide-2/preview-slide-2.png'),
    preview_slider_3: require('./preview-slide-3/preview-slide-3.png'),
    preview_slider_4: require('./preview-slide-4/preview-slide-4.png'),
    pass_checkbox_empty: require('./pass-checkbox-empty/pass-checkbox-empty.png'),
    pass_checkbox_checked: require('./pass-checkbox-checked/pass-checkbox-checked.png'),
    blue_arrow: require('./cta-small-blue-arrow/cta-small-blue-arrow.png'),
    logo_background: require('./logo-background/logo-background.png')
};

export default images;
