export const ActionTypes = {
    SET_SAT_MODE: 'SET_SAT_MODE',
    COMPLETE_BOT_INSTALL: 'COMPLETE_BOT_INSTALL',
    COMPLETE_CHANNEL_INSTALL: 'COMPLETE_CHANNEL_INSTALL',
    COMPLETE_CONTACTS_LOAD: 'COMPLETE_CONTACTS_LOAD',
    SET_CURRENT_SCENE: 'SET_CURRENT_SCENE',
    REFRESH_TIMELINE: 'REFRESH_TIMELINE',
    REFRESH_CHANNELS: 'REFRESH_CHANNELS',
    REFRESH_CONTACTS: 'REFRESH_CONTACTS',
    SET_LOADED_BOT: 'SET_LOADED_BOT',
    LOGOUT: 'LOGOUT'
};
