export const ActionTypes = {
    SET_SAT_MODE: 'SET_SAT_MODE',
    COMPLETE_BOT_INSTALL: 'COMPLETE_BOT_INSTALL',
    COMPLETE_CHANNEL_INSTALL: 'COMPLETE_CHANNEL_INSTALL',
    COMPLETE_CONTACTS_LOAD: 'COMPLETE_CONTACTS_LOAD',
    COMPLETE_CONVERSATIONS_LOAD: 'COMPLETE_CONVERSATIONS_LOAD',
    SET_CURRENT_SCENE: 'SET_CURRENT_SCENE',
    REFRESH_TIMELINE: 'REFRESH_TIMELINE',
    USER_EMAIL: 'USER_EMAIL',
    REFRESH_CHANNELS: 'REFRESH_CHANNELS',
    REFRESH_CONTACTS: 'REFRESH_CONTACTS',
    SET_LOADED_BOT: 'SET_LOADED_BOT',
    SET_CHANNEL_FILTER: 'SET_CHANNEL_FILTER',
    CLEAR_CHANNEL_FILTER: 'CLEAR_CHANNEL_FILTER',
    SET_CHANNEL_PARTICIPANTS: 'SET_CHANNEL_PARTICIPANTS',
    SET_CHANNEL_TEAM: 'SET_CHANNEL_TEAM',
    SET_ALL_CHATS_DATA: 'SET_ALL_CHATS_DATA',
    LOGOUT: 'LOGOUT'
};
