export const ActionTypes = {
    SET_SAT_MODE: 'SET_SAT_MODE',
    COMPLETE_BOT_INSTALL: 'COMPLETE_BOT_INSTALL',
    COMPLETE_CHANNEL_INSTALL: 'COMPLETE_CHANNEL_INSTALL',
    COMPLETE_CONTACTS_LOAD: 'COMPLETE_CONTACTS_LOAD',
    LOGOUT: 'LOGOUT'
};
